### ISSUE TITLE
Latex writing setup

### ISSUE THREAD

**Issue by krillin666** [Hextical/university-notes#1]
Hello,
First of all congrats on the notes, they are beautiful !

Could you share the setup you use to take notes in the class ? Are they edited a posteriori ?

Thanks !

**Comment by Hextical** [comment]
Sorry for the late reply. Now, that I think of it, I might add this somewhere else in my README or via the wiki. For now, this is heavily unedited. My notes are inspired from Dan Wolczuk (the colour theme at least).

I'm not sure exactly how to answer this question, so let's start from the basics. I'll break my ideas up into sections.

# Preface
- Language: **LaTeX**

You must download a compiler for LaTeX. The most popular cross-platform compiler is [TeX Live](https://www.tug.org/texlive/).

# Beginner
Once you've got that set up (you probably have if you're in Math/CS), let's get right into my personal setup.
- Editor: **VSCode**. I use a variant of that called **VSCodium**, but that's irrelevant here. I would just get *VSCode* if I was on Windows, but *fortunately* I'm on Linux :).
   - Mandatory extension: **LaTeX Workshop**. You must use this to compile LaTeX into a `.pdf`. 

Let's say you have a file called `hello.tex`. If that file is opened in VSCode, then you can compile it into a `.pdf` automatically by saving `hello.tex` due to the extension. Once you have the editor and extension, you'll need to learn the syntax and all that other stuff. For a beginner, I recommend [Overleaf's "Learn LaTeX in 30 minutes"](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes). That will get you started as soon as possible.

# Intermediate
If you're interested in my "theme" or "layout," you'll probably need to learn whatever I have in my `preambles` folder (probably `common.tex`), which is probably a huge pain. Honestly, the only advice I can give to you is that you try to lookup some of the commands I have there and learn from that maybe?

Alright, so let's suppose you're familiar with the syntax (maybe you've already typed assignments for your courses in LaTeX).
You might be wondering "how does this guy type his notes in real-time during class" or something along those lines (maybe you didn't even know that). Well, the idea is macros. If I type `@b` I automatically get `\beta`, saving a great amount of time, especially when typing a lot of Greek letters. I have some macros defined in my file `./.vscode/latex.code-snippets`. There is an extreme amount of time saved with my macros, for example if I type `def` I get 
```
\begin{Definition}{$1}{$2}
   $3
\end{Definition}
```
where I start from $1 and go to $2 and $3 by pressing TAB. A really important note is that you need to have the file structure exactly the same as me, and you must open a `workspace` for the editor. In my case, that file is called `university-notes.code-workspace`. 

There are some more stuff, but I don't want to overwhelm you with the sheer amount of information since I'm not sure what faculty you're from etc., etc. Anyways, good luck. To end off on another note, I started playing around with LaTeX when I was a first year (so back in Sept. 2018) and my most recent notes are a result from a lot of experimenting/asking other people what they think looks good.
